name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts')-${{ hashFiles('buildSrc/**/*.kt') }} }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache IntelliJ
      uses: actions/cache@v1
      with:
        path: ide-plugin/build/idea-sandbox
        key: ${{ runner.os }}-intellij-${{ hashFiles('**/*.gradle.kts')-${{ hashFiles('buildSrc/**/*.kt') }} }}
        restore-keys: |
          ${{ runner.os }}-intellij-

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew build
