name: Release

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:

      - uses: jereksel/issue-release-action@v0.0.0.1
        id: version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          users: 'jereksel'

      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Bump version
        run: |
          ./gradlew releaseVersion -Prelease.version="$VERSION"
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - name: Build
        run: |
          ./gradlew build
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - name: Release
        if: steps.version.outputs.version
        run: |
          ./gradlew bintrayUpload publishPlugins publishPlugin -Pgradle.publish.key="$GRADLE_KEY" -Pgradle.publish.secret="$GRADLE_SECRET"
        env:
          BINTRAY_USER: "jereksel"
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          GRADLE_KEY: ${{ secrets.GRADLE_KEY }}
          GRADLE_SECRET: ${{ secrets.GRADLE_SECRET }}
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}

      - name: Push tag
        if: steps.version.outputs.version
        run: |
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
          git add -A
          git commit -m "Release $VERSION"
          git tag -a "v$VERSION" -m "Version $VERSION"
          git push origin "v$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}

      - uses: jereksel/issue-release-action@v0.0.0.1
        if: always() && steps.version.outputs.version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          status: "${{ job.status }}"